name: Go

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  format:
    name: Check code formatting on ${{ matrix.os }} with Go ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Format Code
        run: go fmt ./...

  dependencies:
    name: Check dependencies on ${{ matrix.os }} with Go ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Tidy Deps
        run: go mod tidy
